[embeddings]

emb_size = 12

method = "sort_dist"  # varients: "random", "sort_dist", "distribution_discr", "approximation" 



[train_test]

use_flexible_normalization = 1  # usage of normalization for every user in depend of deals count

normalization_parameter = 0.8  # relevant if use_flexible_normalization == 0

make_dataset_of_deals = 1  # 0 - dataset of users, 1 - dataset of users deals



[train_model]

# for grid_search
random_iteration = 7

# for catboost training
iterations = [500, 1000, 300]
learning_rate = [0.05, 0.1]
depth = [4, 5]
l2_leaf_reg = [15, 35, 60]

[metrics]

[logging]
api_key="5KHdGGECPvjMaU1x9uobLnGyb"
project_name="risk-profiling"
workspace="pashinskaya03"


